-- 코드를 입력하세요
SELECT A.REST_ID , B.REST_NAME , B.FOOD_TYPE , B.FAVORITES , B.ADDRESS , ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO B
JOIN REST_REVIEW A
ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING B.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, B.FAVORITES DESC